# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
steps:
- script: |
    docker build -t myflaskapp:$(Build.BuildId) .
    docker tag myflaskapp:$(Build.BuildId) mycontainerregistry12345678910.azurecr.io/myflaskapp:$(Build.BuildId)
  displayName: 'Docker Build and Tag'

- task: Docker@2
  inputs:
    containerRegistry: 'credit-prediction-api' # Name of your Azure Container Registry service connection
    repository: 'myflaskapp'
    command: 'push'
    tags: |
      $(Build.BuildId)